xds/testing: fix usage of datetime astimezone (#27010)
It caused failure:

Traceback (most recent call last):
  File "tools/run_tests/run_xds_tests.py", line 3096, in <module>
    datetime.datetime.now().astimezone().strftime("%Y-%m-%dT%H:%M:%S %Z"))
ValueError: astimezone() cannot be applied to a naive datetime