[Python] Fix Sanity Pyyaml python3.15 build error (#43292)
This PR re-enables Python 3.15 for Bazel tests and fixes the Bazel repository resolution failure during generate_projects.sh and bazel query caused by building pyyaml from source on Python 3.15.

### Problem & Error

When running tools/buildgen/generate_projects.sh or evaluating bazel query, rules_python fails during repository resolution for Python 3.15 with the following error:
```sh
ERROR: An error occurred during the fetch of repository 'rules_python++pip+grpc_python_dependencies_315_pyyaml_sdist_d7662337':
...
  File "/tmp/pip-build-env-.../site-packages/Cython/Compiler/Errors.py", line 32, in <module>
    from ..Utils import open_new_file
SystemError: module Cython.Utils uses unknown slot ID 84
ERROR: Failed to build 'pyyaml' when getting requirements to build wheel
We hence disabled Python 3.15 for Bazel tests in https://github.com/grpc/grpc/pull/43376/changes/77237fd248861422b413fada84d81e39ab6f1560 while keeping it in the native Python builds.
```

### Root Cause Analysis
PyYAML 6.0.3 does not provide pre-built binary wheels for Python 3.15. Because MODULE.bazel includes "3.15" in PYTHON_VERSIONS, rules_python falls back to building the source distribution (sdist) using Python 3.15 bundled in rules_python, and requires a Cython version >3.0 while doing a source build.

However, the rules_python version we resolve (2.0.2) maps `3.15` to **CPython 3.15.0a8**, an alpha build from python-build-standalone. Whereas, the cp315 Cython wheels on PyPI are built against the 3.15.0 release candidate.

CPython's ABI is not stable between alphas and RCs: the Cython extension uses a module slot (ID 84)
that the 3.15.0a8 interpreter does not recognize, so importing Cython during the PyYAML sdist build fails with it.

### Solution
The real fix is to upgrade to a rules_python version that ships a 3.15 RC interpreter. That is currently available only in rules_python 2.4.0-rc0. The most recent stable `rules_python` release (2.3.4) doesn't support it yet, so we'll do that upgrade once a stable 2.4.0 release is available.

So as an alternate, this PR disables pyyaml for 3.15 builds until PyYaml releases 3.15 supported wheels.

Closes #43292

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/43292 from sreenithi:fix_315_sanity 0346f240e00ceb9b6c1f13367ced6fbb0a51e788
PiperOrigin-RevId: 991606576