[Python] Handle _InactiveRpcError pytorch exception wrapper edge case (#42644)
Handle an edge case where `_channel._InactiveRpcError` is wrapped by an application (or a third-party framework), and the wrapper incorrectly assumes it'll be possible to initialize and reraise it later with a string "message" argument.

Pytorch's exception wrapper results in `AttributeError: 'str' object has no attribute 'condition'`, see https://github.com/pytorch/pytorch/issues/34130.

Fixes #38713. Details in https://github.com/grpc/grpc/issues/38713#issuecomment-4679005990.

Closes #42644

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/42644 from sergiitk:feat/py/handle-InactiveRpcError-bad-type dce3b80152c24ccf34ebc15f2e55f512994c0218
PiperOrigin-RevId: 930861229