Add missing resource_quota dep to windows_event_engine (#43482)
`windows_engine.cc` includes `src/core/lib/resource_quota/resource_quota.h`, but `//src/core:windows_event_engine` does not declare a dependency on `//src/core:resource_quota`.

This fails `layering_check` with C++ toolchains that enforce it, for example when cross-compiling to Windows with the hermetic LLVM toolchains from the `llvm` Bazel module:

```
external/grpc+/src/core/lib/event_engine/windows/windows_engine.cc:45:10: error: module @@grpc+//src/core:windows_event_engine does not depend on a module exporting 'src/core/lib/resource_quota/resource_quota.h'
```

Found while cross-compiling Bazel itself to Windows.

Closes #43482

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/43482 from fmeum:windows-event-engine-resource-quota-dep b9e00bd01b2b5753c9b50b2bc7fd15a5a9780a3c
PiperOrigin-RevId: 985807497