[PSM Interop] Legacy driver: freeze pip deps (#40438)
Fixes pip dependency conflicts in the legacy test driver install script:

```
/tmp/tmp.wkky1LYPKI/bin/python -m pip install --upgrade grpcio grpcio-tools==1.48.1 google-api-python-client google-auth-httplib2 oauth2client xds-protos
. . .
Collecting xds-protos
  Downloading https://files.pythonhosted.org/packages/c7/a3/bf45208f2c18e59ef3d2093e4a972481f7f8485951ec31b5009163fc64d9/xds_protos-1.74.0-py3-none-any.whl (1.2MB)
. . .
ERROR: xds-protos 1.74.0 has requirement protobuf<7.0.0,>=6.31.1, but you'll have protobuf 3.20.3 which is incompatible.
    Running setup.py install for grpcio-tools: started
    Running setup.py install for grpcio-tools: finished with status 'error'
```

This PR:
- Freezes legacy driver's pip dependencies
- Synchronizes grpc_xds_bazel_test_in_docker.sh, grpc_xds_bazel_python_test_in_docker.sh, prep_xds.sh
- Improves command date logging

ref b/438434981

Closes #40438

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40438 from sergiitk:fix/psm/legacy/pip-freeze 0872687f10178fe4274f348e5dc0435cafc2da9e
PiperOrigin-RevId: 795111220