update cares to version cares-1_15_0
This fixes the issue: https://github.com/grpc/grpc/issues/16688

Which causes that grpc can not be build because of the following
compiler error:
  third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
  third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer- memaccess] sizeof(src->local_dev_name));