[CI] Fix windows grpc_portability (#42179)
The failure wasn't due to a race condition or threading issue as it was a compiler-dependent string formatting issue!

The failure output showed:
```
error: Expected equality of these values:
  metadata->DebugString().c_str()
    Which is: "grpc-status: UNAVAILABLE, grpc-message: Connection closed, GrpcCallWasCancelled: true"
  "grpc-message: Connection closed, grpc-status: UNAVAILABLE, GrpcCallWasCancelled: true"
```

The string elements generated by metadata->DebugString() are correct, but they are printed in a different order on Windows MSVC compared to Linux GCC/Clang.

Closes #42179

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/42179 from rishesh007:portability_fix_windows 9f9a8eaffe9070df56e07eaa0acbe622d60941aa
PiperOrigin-RevId: 902453435