Convince the compiler that the lock is held
Without this change, attempting to compile this in the Fuchsia tree:

```
  In file included from ../../third_party/grpc/src/cpp/server/server_cc.cc:18:
  In file included from ../../third_party/grpc/include/grpcpp/server.h:30:
  In file included from ../../third_party/grpc/include/grpcpp/channel.h:28:
  In file included from ../../third_party/grpc/include/grpcpp/impl/codegen/completion_queue.h:43:
  ../../third_party/grpc/include/grpcpp/impl/codegen/sync.h:148:11: error: calling function 'operator()' requires holding mutex 'mu_' exclusively [-Werror,-Wthread-safety-analysis]
    while (!pred()) {
            ^
  ../../third_party/grpc/src/cpp/server/server_cc.cc:1113:19: note: in instantiation of function template specialization 'grpc::internal::WaitUntil<(lambda at ../../third_party/grpc/src/cpp/server/server_cc.cc:1115:7)>' requested here
    grpc::internal::WaitUntil(
                    ^
  1 error generated.
```

This seems to be required because the compiler does its analysis
function-by-function. In WaitUntil, the compiler can't see that the lock
required by the passed lambda is held by WaitUntil's caller.

Change-Id: I3386c1cfae0fec62e1703efb972ddeb940084827