Fix bazel query //tools/distrib/python/grpcio_tools/... (#40236)
Exclude generated directories in grpcio_tools that prevent bazel
recursive queries.

```sh-session
$ # before
$ bazel query //tools/distrib/python/grpcio_tools/...
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 8.0.1 will be used instead of system-wide bazel installation.
ERROR: error loading package under directory 'tools/distrib/python/grpcio_tools': error loading package 'tools/distrib/python/grpcio_tools/third_party/protobuf/upb/reflection': Label '//upb_generator:bootstrap_compiler.bzl' is invalid because 'upb_generator' is not a package; perhaps you meant to put the colon here: '//:upb_generator/bootstrap_compiler.bzl'?
$ # after
$ bazel query //tools/distrib/python/grpcio_tools/...
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 8.0.1 will be used instead of system-wide bazel installation.
//tools/distrib/python/grpcio_tools:cyprotoc
//tools/distrib/python/grpcio_tools:grpc_tools
//tools/distrib/python/grpcio_tools:grpc_tools/_protoc_compiler.pyx_cython_translation
//tools/distrib/python/grpcio_tools:grpc_tools/_protoc_compiler.so
//tools/distrib/python/grpcio_tools:protoc_lib
//tools/distrib/python/grpcio_tools:well_known_protos
//tools/distrib/python/grpcio_tools:well_known_protos_symlink
//tools/distrib/python/grpcio_tools/grpc_tools/test:complicated_proto
//tools/distrib/python/grpcio_tools/grpc_tools/test:complicated_py_pb2
//tools/distrib/python/grpcio_tools/grpc_tools/test:protoc_test
//tools/distrib/python/grpcio_tools/grpc_tools/test:simplest_proto
```

The exclude list is based on
`tools/distrib/python/grpcio_tools/.gitignore`.