Fix GRPC_CHECK_NE comparison for session_holder_ in QPS client.
Use session_holder_.get() instead of comparing the smart pointer directly to nullptr, which ensures compatibility with the GRPC_CHECK_NE macro. This  fixes errors such as

```
/b/f/w/bazel-out/k8-fastbuild/bin/tools/bazelify_tests/test/runtests_cpp_linux_dbg_gcc_12_openssl309_build_only.runfiles/_main/grpc/cmake/install/include/absl/log/internal/check_op.h:298:43: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const std::unique_ptr<grpc::testing::SessionHolder>’)
```

because unique_ptr does not support the "<<" operator that is needed by the CHECK implementation.

PiperOrigin-RevId: 974524459