[Python] Fix Observability linker error in PSM Interop tests (#40661)
The PSM Interop Python tests started failing from Sept 3rd with the below error after https://github.com/grpc/grpc/pull/40532/ was submitted on Sept 2. (Internal ref: b/440024603)
```
Traceback (most recent call last):
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_py3_only/interop/xds_interop_client.py", line 39, in <module>
    from grpc_csm_observability import CsmOpenTelemetryPlugin
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_csm_observability/grpc_csm_observability/__init__.py", line 14, in <module>
    from grpc_csm_observability._csm_observability_plugin import (
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_csm_observability/grpc_csm_observability/_csm_observability_plugin.py", line 20, in <module>
    from grpc_observability._observability import OptionalLabelType
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_observability/grpc_observability/__init__.py", line 15, in <module>
    from grpc_observability._open_telemetry_plugin import OpenTelemetryPlugin
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_observability/grpc_observability/_open_telemetry_plugin.py", line 18, in <module>
    from grpc_observability import _open_telemetry_observability
  File "/xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_observability/grpc_observability/_open_telemetry_observability.py", line 23, in <module>
    from grpc_observability import _cyobservability
ImportError: /xds_interop_client.runfiles/com_github_grpc_grpc/src/python/grpcio_observability/grpc_observability/_cyobservability.so: undefined symbol: gpr_inf_future
```

#40532 added a new dependency target `//src/core:instrument` in the [observability build](https://github.com/grpc/grpc/pull/40532/files#diff-327f36df2c4296ca22a20c02acf8ab1cb3250aa7ec5364c5a2bd6ea28a2d7851R105) and a call to `grpc_core::CreateCollectionScope();` in [src/python/grpcio_observability/grpc_observability/observability_util.cc](https://github.com/grpc/grpc/pull/40532/files#diff-b8e941596f8e2ca80522ba2a2a519191ea19932bc41ffd02dab5ce9bb9f37995R98) to force link the instrument package.

The Interop test that caught the error runs the Bazel test: `tools/bazel run -c dbg --config=python //src/python/grpcio_tests/tests_py3_only/interop:xds_interop_server`

Investigating through the Bazel build dependencies of `_cyobservability` and the newly added `//src/core:instrument` dependency, it was found that
1. `//src/core:instrument` depends on `//src/core:sync`
2. `//src/core:sync` depends on `//src/core:time_util`
which defines `src/core/util/time_util.cc` referencing symbols like `gpr_inf_future`

`gpr_inf_future` and other related gpr time symbols are **declared** in `include/grpc/support/time.h` which is one of the dependencies of `//src/core:time_util`, however the **definition** of `gpr_inf_future` is in `src/core/util/gpr_time.cc`  (Bazel target `//src/core:gpr_time`) which is currently not a dependency of `//src/core:time_util`.

While it was the Python observability test that flagged this error and adding `//src/core:gpr_time` as a dependency to `cyobservability` can also solve this error, I think it is more relevant and clean to add it in `//src/core:time_util`. Hence changing so in this PR.

Closes #40661

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40661 from sreenithi:try_fixing_observability_linker_error 2c67e2a27b830362f1230ec762fc985b7cdd2738
PiperOrigin-RevId: 806299291