[Python] Make protoc_test work python > 3.7 on macos, windows (#40253)
In Python 3.8, multiprocessing module changed the default fork method from `fork` to `spawn`:

> On macOS, the spawn start method is now used by default.
> — https://docs.python.org/3/whatsnew/3.8.html#multiprocessing

Spawn method uses pickling to pass the target method to the fork. Pickling is only supported for top-level defined methods. This PR changes the test wrapper to use an annotation to collect test result instead of `_wrap_in_subprocess`, therefore making the method picklable by keeping the method definition at the top level. Similar to https://github.com/grpc/grpc/blob/9772d150772f50ab0eb0b7f2e8e88196fee333c2/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py#L47.

Steps to reproduce:
```console
$ sw_vers
ProductName:		macOS
ProductVersion:		15.5
BuildVersion:		24F74
$ cd tools/distrib/python/grpcio_tools/grpc_tools/test/
$ python3.9 -m venv --upgrade-deps .venv
$ source .venv/bin/activate
$ pip install grpcio grpcio-tools
$ python protoc_test.py
```

Before:
```console
$ python protoc_test.py
EEEEEEE
======================================================================
ERROR: test_combined_import (__main__.ProtocTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sergiitk/Development/grpc/tools/distrib/python/grpcio_tools/grpc_tools/test/protoc_test.py", line 168, in test_combined_import
    _run_in_subprocess(_test_combined_import)
  File "/Users/sergiitk/Development/grpc/tools/distrib/python/grpcio_tools/grpc_tools/test/protoc_test.py", line 45, in _run_in_subprocess
    proc.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function _test_combined_import at 0x10c2a0f70>: it's not the same object as __main__._test_combined_import
...
```

After
```console
$ python protoc_test.py
.......
----------------------------------------------------------------------
Ran 7 tests in 2.568s

OK
```

Closes #40253

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40253 from sergiitk:fix/macos/protoc_test 658fbecbbe3eca41249034819a2ae1a5a5c1e776
PiperOrigin-RevId: 786101961