Use uintptr_t to represent pointers
With HWASan, the top bit of the pointer may be used, so using intptr_t leads to

```
OverflowError: Python int too large to convert to C ssize_t
```