[Python] Use uintptr_t to represent _ChannelArg.c_argument pointers (#42016)
With HWASan, the top bit of the pointer may be used, so using intptr_t leads to

```
OverflowError: Python int too large to convert to C ssize_t
```

Closes #42016

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/42016 from fmayer:patch-1 b34fefe23b5c69ea99c9bfbb647b98f15875e73f
PiperOrigin-RevId: 907116150