[Python Observability] Allow create call with registered method (#35002)
Based on [OpenTelemetry Metrics gRFC](https://github.com/grpc/proposal/blob/master/A66-otel-stats.md#opentelemetry-metrics), we should recored unregistered RPC method name as `other`, this PR adds the ability to pass register method information when creating a call.

We'll consider calls created using generated stubs as registered, note that this won't prevent user from setting `registered_method=True` when creating calls manually.

This is also enabled for simple stub flow but **NOT enabled for AsyncIO**, we'll add that later when start working on AsyncIO Observability.

Note:
* **Distribution Tests Python Windows** test failed with error `AttributeError: module 'setuptools.errors' has no attribute 'CompileError'`, it's because we're using low version of setuptools for windows 3.7. I don't think the underlay issue is related to this PR, I tried debug it in this run but it passed: https://fusion2.corp.google.com/invocations/565f0f90-5965-40ca-b6b6-dc7ddc24e46a
<!--

If you know who should review your pull request, please assign it to that
person, otherwise the pull request would get assigned randomly.

If your pull request is for a specific language, please add the appropriate
lang label.

-->

Closes #35002

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/35002 from XuanWang-Amos:add_registered_method 45a68b147cf744740df9abb91783f12c4a32dc95
PiperOrigin-RevId: 584141205