[Fix] Added missing #include (#34339)
To fix the following build error with the head of abseil

```
/var/local/git/grpc/test/core/tsi/ssl_transport_security_utils_test.cc:231:42: error: no member named 'StrCat' in namespace 'absl'
        return absl::InternalError(absl::StrCat("Client error:", client_err));
                                   ~~~~~~^
/var/local/git/grpc/test/core/tsi/ssl_transport_security_utils_test.cc:238:42: error: no member named 'StrCat' in namespace 'absl'
        return absl::InternalError(absl::StrCat("Server error:", server_err));
                                   ~~~~~~^
```