[Test] Fixed unused warnings (#40103)
Fixed this unused warning

```
In file included from src/cpp/server/channelz/channelz_service_plugin.cc:28:
./src/cpp/server/channelz/channelz_service.h:73:62: error: unused parameter 'request' [-Werror,-Wunused-parameter]
      ServerContext*, const channelz::v2::QueryTraceRequest* request,
                                                             ^
./src/cpp/server/channelz/channelz_service.h:74:55: error: unused parameter 'writer' [-Werror,-Wunused-parameter]
      ServerWriter* writer) override {
```

Closes #40103

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40103 from veblush:fix-war 86621f67875e17780ff0e5d4e7da6b04a56c522c
PiperOrigin-RevId: 778704686