check for needed protobuf version
in the meanwhile updated to 3.5.0

in case protobuf is installed on the system and pkg-config can be used
the version check has to be against 3.4.0. Otherwise you run into:

./src/compiler/php_generator_helpers.h: In function ‘grpc::string grpc_php_generator::GetPHPServiceFilename(const FileDescriptor*, const ServiceDescriptor*, const string&)’:
./src/compiler/php_generator_helpers.h:51:23: error: ‘const class google::protobuf::FileOptions’ has no member named ‘has_php_namespace’; did you mean ‘has_csharp_namespace’?
   if (file->options().has_php_namespace()) {
                       ^~~~~~~~~~~~~~~~~
                       has_csharp_namespace
./src/compiler/php_generator_helpers.h:52:39: error: ‘const class google::protobuf::FileOptions’ has no member named ‘php_namespace’; did you mean ‘csharp_namespace’?
     oss << ReplaceAll(file->options().php_namespace(), "\\", "/");
                                       ^~~~~~~~~~~~~
                                       csharp_namespace
src/compiler/php_generator.cc: In function ‘grpc::string grpc_php_generator::{anonymous}::PackageName(const FileDescriptor*)’:
src/compiler/php_generator.cc:47:23: error: ‘const class google::protobuf::FileOptions’ has no member named ‘has_php_namespace’; did you mean ‘has_csharp_namespace’?
   if (file->options().has_php_namespace()) {
                       ^~~~~~~~~~~~~~~~~
                       has_csharp_namespace
src/compiler/php_generator.cc:48:28: error: ‘const class google::protobuf::FileOptions’ has no member named ‘php_namespace’; did you mean ‘csharp_namespace’?
     return file->options().php_namespace();
                            ^~~~~~~~~~~~~
                            csharp_namespace