Propose a fix for GRP_DEBUG_ASSERT failures seen in Google-internal library
Context: An internal change to the Scaffolding framework included a third party grpc header file (grpc/include/grcpp/security/server_credentials.h) into some google3 code, and an internal library's build started to break with the following error:
```
third_party/grpc/include/grpcpp/support/callback_common.h:210:33: error: reference to non-static member function must be called; did you mean to call it with no arguments?
    GPR_DEBUG_ASSERT(ignored == ops);
                                ^~~
third_party/grpc/include/grpc/support/log.h:103:40: note: expanded from macro 'GPR_DEBUG_ASSERT'
#define GPR_DEBUG_ASSERT(x) GPR_ASSERT(x)
                                       ^
third_party/grpc/include/grpc/support/log.h:97:24: note: expanded from macro 'GPR_ASSERT'
    if (GPR_UNLIKELY(!(x))) {                       \
                       ^
./third_party/grpc/include/grpc/support/port_platform.h:754:43: note: expanded from macro 'GPR_UNLIKELY'
#define GPR_UNLIKELY(x) __builtin_expect((x), 0)
```
It seems that when compiling, NDEBUG is defined, so the line `auto* ops = ops_;` is removed by the preprocessor. However, the GPR_DEBUG_ASSERT macro still expands to something like the following:
```
#ifndef NDEBUG
  do { ... } while (0);
#endif
```
When compiled in "non-optimized mode" with blaze (i.e. without -c opt), it seems like the contents of the loop are evaluated, so the symbol will need to be declared.

This proposed fix unblocks the original internal Scaffolding change (which had to be rolled back). I have also confirmed internally that this fixes the build error mentioned above.