[Fix][Python] Pin pip version to 25.2 in Python tests (#40959)
Pip released [v25.3](https://pip.pypa.io/en/stable/news/#v25-3) a few days back which doesn't support `setup.py` builds anymore, while we are yet to migrate to use the `pyproject.toml` build system in #40833.

Hence some of our Python tests using the most recent versions of pip for the build have started to fail with errors like:
```
  ERROR: Failed building wheel for grpcio
Failed to build grpcio
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
```

This PR hence pins the pip version to 25.2 which still supports setup.py build until #40833 is submitted.

Closes #40959

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40959 from sreenithi:pin_pip_version d72e0563ce0f00a962bd03ddd279cf587494fd3e
PiperOrigin-RevId: 824584176