[Build] Added missing useful to cf_event_engine (#40209)
Fixed the layering issue found in https://github.com/bazelbuild/bazel-central-registry/pull/5139

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/grpc~/src/core/lib/event_engine/cf_engine/cf_engine.cc:34:10: error: module grpc~//src/core:cf_event_engine does not depend on a module exporting 'src/core/util/useful.h'
   34 | #include "src/core/util/useful.h"
      |          ^
```

Closes #40209

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/40209 from veblush:useful-mac 6a40386e457e0cc6e600a69352b52dbbc93b0536
PiperOrigin-RevId: 783160418