[ObjC] use c++17 in spm package and add a build test (#38949)
Build fails with errors like the following which requires c++17
```
/Users/hannahshi/work/grpc/spm-core-include/grpc/event_engine/endpoint_config.h:36:11: error: no template named 'optional' in namespace 'std'; did you mean 'absl::optional'?
   36 |   virtual std::optional<int> GetInt(absl::string_view key) const = 0;
      |           ^~~~~~~~~~~~~
      |           absl::optional
```
```
/Users/hannahshi/work/grpc/src/core/lib/promise/detail/promise_factory.h:169:31: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
  169 |                          std::is_same_v<ResultOf<F()>, void>,
      |                          ~~~~~^~~~~~~~~
      |                               is_same
```

Closes #38949

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/38949 from HannahShiSFB:update-swift-package-to-cpp17 a5a4ffdbef425a6e9a27c5fc24f281c938849502
PiperOrigin-RevId: 735619641