[Build] Bump ndk version to unblock protobuf 33.x upgrade. (#41944)
The ndk version is too old and causes some compiler bug with ARM ABIs when clang attribute `musttail` is specified.

```
FAILED: ../grpc/outputs/armeabi-v7a/CMakeFiles/upb_mini_descriptor_lib.dir/third_party/upb/upb/wire/decode_fast/dispatch.c.o
  /opt/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi21 --sysroot=/opt/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I/var/local/jenkins/grpc/third_party/re2 -I/var/local/jenkins/grpc/third_party/zlib -I/var/local/jenkins/grpc/include -I/var/local/jenkins/grpc -I/var/local/jenkins/grpc/third_party/address_sorting/include -I/var/local/jenkins/grpc/src/android/test/interop/app/.cxx/Debug/3c1u1s4p/grpc/outputs/armeabi-v7a/third_party/re2 -I/var/local/jenkins/grpc/third_party/boringssl-with-bazel/src/include -I/var/local/jenkins/grpc/src/core/ext/upb-gen -I/var/local/jenkins/grpc/src/core/ext/upbdefs-gen -I/var/local/jenkins/grpc/third_party/upb -I/var/local/jenkins/grpc/third_party/utf8_range -I/var/local/jenkins/grpc/third_party/xxhash -I/var/local/jenkins/grpc/src/android/test/interop/app/.cxx/Debug/3c1u1s4p/grpc/outputs/armeabi-v7a/third_party/zlib -I/var/local/jenkins/grpc/third_party/abseil-cpp -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -pthread -MD -MT ../grpc/outputs/armeabi-v7a/CMakeFiles/upb_mini_descriptor_lib.dir/third_party/upb/upb/wire/decode_fast/dispatch.c.o -MF ../grpc/outputs/armeabi-v7a/CMakeFiles/upb_mini_descriptor_lib.dir/third_party/upb/upb/wire/decode_fast/dispatch.c.o.d -o ../grpc/outputs/armeabi-v7a/CMakeFiles/upb_mini_descriptor_lib.dir/third_party/upb/upb/wire/decode_fast/dispatch.c.o -c /var/local/jenkins/grpc/third_party/upb/upb/wire/decode_fast/dispatch.c
  fatal error: error in backend: failed to perform tail call elimination on a call site marked musttail
```

<!--

If you know who should review your pull request, please assign it to that
person, otherwise the pull request would get assigned randomly.

If your pull request is for a specific language, please add the appropriate
lang label.

-->

Closes #41944

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/41944 from yuanweiz:android-gradle c49f4612a8149e09ba897cb3b1f7e7e89fb0b608
PiperOrigin-RevId: 891787114