decrease concurrency for windows grpc_distribtests_python (#38161)
Decrease concurrency for Python distribution tests on Windows

```
Compiler terminating.  Please wait........... Abort complete.
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 508, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
    return super().spawn(cmd, env=env)
  File "T:\altsrc\github\grpc\workspace_python_windows_x64_Python310\src\python\grpcio\_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, modified_command, **kwargs)
  File "C:\Python310\lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "C:\Python310\lib\site-packages\setuptools\_distutils\spawn.py", line 68, in spawn
    raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\link.exe' failed with exit code 4
```

What is [exit code 4 ](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-#:~:text=ERROR_TOO_MANY_OPEN_FILES,open%20the%20file.)
The tests are timing out on kokoro windows

We have added support for 3.12 python version but have not dropped support for any older version. hence overall number of tests have increased.

Closes #38161

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/38161 from sourabhsinghs:bugfix/kokoro-windows 94e51a51e42c480a0531a560eb7925eff1d6d662
PiperOrigin-RevId: 704568179