[Fix][CI] macOS jobs: Partially undo gnupg workaround #42403 to use cached sources (#43217)
This fixes the issue with the main GnuPG sources site being down at the moment.

```
$ xh -h https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.4.8.tar.bz2
HTTP/1.1 403 Forbidden
Connection: Keep-Alive
Content-Length: 275
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 12 Aug 2026 22:36:33 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.56 (Debian)
```

This caused all MacOS Kokoro jobs to fail with:
```
++ brew install --build-from-source gnupg
...
Error: Failed to download resource "gnupg (2.4.8)"
Download failed: [https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.4.8.tar.bz2](https://www.google.com/url?q=https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.4.8.tar.bz2&sa=D)
```

https://source.cloud.google.com/results/invocations/1cbfa293-bb04-4d44-9b74-68f0231230f4

I tried to undo #42403 fully, but we're still broken:

```
==> Installing dependencies for gnupg: ca-certificates, libunistring, json-c, gettext, libtasn1, nettle, p11-kit, gnutls, libgpg-error, libassuan, libgcrypt, libksba, libusb, npth and pinentry
==> Installing gnupg dependency: ca-certificates
==> Pouring ca-certificates--2026-07-16.all.bottle.2.tar.gz
Error: undefined method '[]' for nil
```

Surprisingly, removing `brew install --build-from-source gnupg` fixes everything. Why? No idea. Maybe it wasn't necessary for #42403 fix to work in the first place.

On a semi-related note, I learned is that we actually had `gnupg (2.4.8)` sources cached on the VM already:

```
++ brew --cache --build-from-source gnupg
/Users/kbuilder/Library/Caches/Homebrew/downloads/f3fa6052a2929df4e614d315998cfa23fd3ad51db8f50c298603933b3e592858--gnupg-2.4.8.tar.bz2
```

(note that `brew --cache --build-from-source gnupg` is not the same as `brew install --build-from-source gnupg`: it just prints the cached path).

Closes #43217

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/43217 from sergiitk:fix/ci/macos/brew-no-gpkg-source 15888a8eed47994aff2d3c02d06bc8b88a7c8c18
PiperOrigin-RevId: 963734913